// src/app/agenda/data-mock.ts

export type AgendaItem = {
    id: string;
    nome: string;
    date: string;
    dayKey: string;
    dayLabel: string;
    time: string;
    tags: string[];
    speakerNames: string[];
    publico: string;
    status: string;
    track: string;
    area: string[];
    tipoConteudo: string;
    topics: string;
    description: string;
    bigDescription: string;
};

export const MOCK_NOTION_DATA: AgendaItem[] = [
    // --- DIA 1: SEXTA-FEIRA (30/05) ---
    {
        id: "1",
        nome: "Check-in & Café de Boas-vindas",
        date: "2025-05-30T08:00:00.000-03:00",
        dayKey: "2025-05-30",
        dayLabel: "sexta-feira, 30 de maio",
        time: "08:00",
        tags: ["Networking"],
        speakerNames: [],
        publico: "Geral",
        status: "Pronto",
        track: "Hall de Entrada",
        area: [],
        tipoConteudo: "Abertura",
        topics: "",
        description: "Credenciamento e retirada de kits.",
        bigDescription: "",
    },
    {
        id: "2",
        nome: "Keynote: O Futuro da Tecnologia em 2030",
        date: "2025-05-30T09:00:00.000-03:00",
        dayKey: "2025-05-30",
        dayLabel: "sexta-feira, 30 de maio",
        time: "09:00",
        tags: ["Inovação", "Futuro", "IA"],
        speakerNames: ["Ana Silva"],
        publico: "Geral",
        status: "Pronto",
        track: "Main Stage",
        area: ["Carreira"],
        tipoConteudo: "Palestra Principal",
        topics: "IA Generativa; Mercado Tech; Computação Quântica",
        description: "Uma visão sobre o que nos espera nos próximos anos e como se preparar.",
        bigDescription: "Nesta palestra de abertura, Ana Silva (CTO da TechCorp) explora as tendências emergentes que moldarão a próxima década. Da IA generativa à computação quântica, entenda onde focar seus estudos.",
    },
    // SIMULTÂNEA 1 (10:30)
    {
        id: "3",
        nome: "Arquitetura de Microsserviços em Escala",
        date: "2025-05-30T10:30:00.000-03:00",
        dayKey: "2025-05-30",
        dayLabel: "sexta-feira, 30 de maio",
        time: "10:30",
        tags: ["Backend", "Arquitetura"],
        speakerNames: ["Carlos Dev", "Roberto Tech"],
        publico: "Avançado",
        status: "Pronto",
        track: "Main Stage",
        area: ["Engenharia"],
        tipoConteudo: "Painel de Discussão",
        topics: "Escalabilidade; Kubernetes; Event-Driven",
        description: "Discussão profunda sobre quando usar (e quando NÃO usar) microsserviços.",
        bigDescription: "Um debate técnico honesto sobre os desafios de migrar monólitos para microsserviços. Nossos especialistas compartilham histórias de guerra e lições aprendidas em produção.",
    },
    // SIMULTÂNEA 2 (10:30)
    {
        id: "4",
        nome: "UX Writing: Como escrever para interfaces",
        date: "2025-05-30T10:30:00.000-03:00",
        dayKey: "2025-05-30",
        dayLabel: "sexta-feira, 30 de maio",
        time: "10:30",
        tags: ["Design", "UX"],
        speakerNames: ["Mariana Texto"],
        publico: "Iniciante",
        status: "Pronto",
        track: "Design Room",
        area: ["Produto"],
        tipoConteudo: "Workshop Prático",
        topics: "Microcopy; Acessibilidade; Voz e Tom",
        description: "Aprenda na prática como textos claros melhoram a experiência do usuário.",
        bigDescription: "Neste workshop, vamos reescrever telas reais de aplicativos famosos para torná-las mais acessíveis e amigáveis. Traga seu notebook!",
    },
    {
        id: "5",
        nome: "Pausa para Almoço",
        date: "2025-05-30T12:00:00.000-03:00",
        dayKey: "2025-05-30",
        dayLabel: "sexta-feira, 30 de maio",
        time: "12:00",
        tags: [],
        speakerNames: [],
        publico: "Geral",
        status: "Pronto",
        track: "Área de Convivência",
        area: [],
        tipoConteudo: "Pausa",
        topics: "",
        description: "Momento livre para alimentação e networking.",
        bigDescription: "",
    },
    // SIMULTÂNEA 3 (14:00)
    {
        id: "6",
        nome: "React Server Components: O Guia Definitivo",
        date: "2025-05-30T14:00:00.000-03:00",
        dayKey: "2025-05-30",
        dayLabel: "sexta-feira, 30 de maio",
        time: "14:00",
        tags: ["Frontend", "React", "Next.js"],
        speakerNames: ["Lucas Front"],
        publico: "Intermediário",
        status: "Pronto",
        track: "Main Stage",
        area: ["Desenvolvimento"],
        tipoConteudo: "Palestra Principal",
        topics: "RSC; Performance; Streaming",
        description: "Entenda de vez como funcionam os Server Components.",
        bigDescription: "Chega de confusão. Vamos desmistificar o render e mostrar como migrar sua aplicação para usar o melhor dos dois mundos (Server e Client).",
    },
    // SIMULTÂNEA 4 (14:00)
    {
        id: "7",
        nome: "Segurança em Cloud Native",
        date: "2025-05-30T14:00:00.000-03:00",
        dayKey: "2025-05-30",
        dayLabel: "sexta-feira, 30 de maio",
        time: "14:00",
        tags: ["DevSecOps", "Cloud"],
        speakerNames: ["Fernanda Cyber"],
        publico: "Avançado",
        status: "Pronto",
        track: "Dev Stage",
        area: ["Segurança"],
        tipoConteudo: "Workshop Prático",
        topics: "IAM; Containers; Zero Trust",
        description: "Protegendo sua infraestrutura contra ameaças modernas.",
        bigDescription: "Uma demonstração ao vivo de como hackers exploram falhas em containers mal configurados e como você pode se proteger.",
    },

    // --- DIA 2: SÁBADO (31/05) ---
    {
        id: "8",
        nome: "Café da Manhã & Mentoria",
        date: "2025-05-31T09:00:00.000-03:00",
        dayKey: "2025-05-31",
        dayLabel: "sábado, 31 de maio",
        time: "09:00",
        tags: ["Carreira"],
        speakerNames: ["Mentores Tech Start"],
        publico: "Geral",
        status: "Pronto",
        track: "Área de Convivência",
        area: ["Carreira"],
        tipoConteudo: "Abertura",
        topics: "",
        description: "Rodadas de conversa com líderes de mercado.",
        bigDescription: "",
    },
    {
        id: "9",
        nome: "Data Engineering: Do Lake ao Lakehouse",
        date: "2025-05-31T10:00:00.000-03:00",
        dayKey: "2025-05-31",
        dayLabel: "sábado, 31 de maio",
        time: "10:00",
        tags: ["Dados", "Engenharia"],
        speakerNames: ["João Dados"],
        publico: "Intermediário",
        status: "Pronto",
        track: "Main Stage",
        area: ["Dados"],
        tipoConteudo: "Palestra Principal",
        topics: "ETL; Big Data; Spark",
        description: "A evolução das arquiteturas de dados modernas.",
        bigDescription: "",
    },
    {
        id: "10",
        nome: "Encerramento e Sorteios",
        date: "2025-05-31T12:00:00.000-03:00",
        dayKey: "2025-05-31",
        dayLabel: "sábado, 31 de maio",
        time: "12:00",
        tags: [],
        speakerNames: ["Organização"],
        publico: "Geral",
        status: "Pronto",
        track: "Main Stage",
        area: [],
        tipoConteudo: "Abertura",
        topics: "",
        description: "Agradecimentos finais e sorteio de brindes.",
        bigDescription: "",
    },
];